#pragma once

// System.Linq.Enumerable/<CreateSelectIterator>c__Iterator10`2<<>f__AnonymousType0`2<System.Reflection.ConstructorInfo,System.Reflection.ParameterInfo[]>,<>f__AnonymousType1`2<<>f__AnonymousType0`2<System.Reflection.ConstructorInfo,System.Reflection.ParameterInfo[]>,System.Collections.Generic.IEnumerable`1<System.Type>>>
struct U3CCreateSelectIteratorU3Ec__Iterator10_2_t5313;
// <>f__AnonymousType1`2<<>f__AnonymousType0`2<System.Reflection.ConstructorInfo,System.Reflection.ParameterInfo[]>,System.Collections.Generic.IEnumerable`1<System.Type>>
struct U3CU3Ef__AnonymousType1_2_t510;
// System.Object
struct Object_t;
// System.Collections.IEnumerator
struct IEnumerator_t30;
// System.Collections.Generic.IEnumerator`1<<>f__AnonymousType1`2<<>f__AnonymousType0`2<System.Reflection.ConstructorInfo,System.Reflection.ParameterInfo[]>,System.Collections.Generic.IEnumerable`1<System.Type>>>
struct IEnumerator_1_t5314;

// System.Void System.Linq.Enumerable/<CreateSelectIterator>c__Iterator10`2<<>f__AnonymousType0`2<System.Reflection.ConstructorInfo,System.Reflection.ParameterInfo[]>,<>f__AnonymousType1`2<<>f__AnonymousType0`2<System.Reflection.ConstructorInfo,System.Reflection.ParameterInfo[]>,System.Collections.Generic.IEnumerable`1<System.Type>>>::.ctor()
// System.Linq.Enumerable/<CreateSelectIterator>c__Iterator10`2<System.Object,System.Object>
#include "System_Core_System_Linq_Enumerable_U3CCreateSelectIteratorU3_0MethodDeclarations.h"
#define U3CCreateSelectIteratorU3Ec__Iterator10_2__ctor_m22556(__this, method) (void)U3CCreateSelectIteratorU3Ec__Iterator10_2__ctor_m15287_gshared((U3CCreateSelectIteratorU3Ec__Iterator10_2_t4351 *)__this, method)
// TResult System.Linq.Enumerable/<CreateSelectIterator>c__Iterator10`2<<>f__AnonymousType0`2<System.Reflection.ConstructorInfo,System.Reflection.ParameterInfo[]>,<>f__AnonymousType1`2<<>f__AnonymousType0`2<System.Reflection.ConstructorInfo,System.Reflection.ParameterInfo[]>,System.Collections.Generic.IEnumerable`1<System.Type>>>::System.Collections.Generic.IEnumerator<TResult>.get_Current()
#define U3CCreateSelectIteratorU3Ec__Iterator10_2_System_Collections_Generic_IEnumeratorU3CTResultU3E_get_Current_m22557(__this, method) (U3CU3Ef__AnonymousType1_2_t510 *)U3CCreateSelectIteratorU3Ec__Iterator10_2_System_Collections_Generic_IEnumeratorU3CTResultU3E_get_Current_m15288_gshared((U3CCreateSelectIteratorU3Ec__Iterator10_2_t4351 *)__this, method)
// System.Object System.Linq.Enumerable/<CreateSelectIterator>c__Iterator10`2<<>f__AnonymousType0`2<System.Reflection.ConstructorInfo,System.Reflection.ParameterInfo[]>,<>f__AnonymousType1`2<<>f__AnonymousType0`2<System.Reflection.ConstructorInfo,System.Reflection.ParameterInfo[]>,System.Collections.Generic.IEnumerable`1<System.Type>>>::System.Collections.IEnumerator.get_Current()
#define U3CCreateSelectIteratorU3Ec__Iterator10_2_System_Collections_IEnumerator_get_Current_m22558(__this, method) (Object_t *)U3CCreateSelectIteratorU3Ec__Iterator10_2_System_Collections_IEnumerator_get_Current_m15289_gshared((U3CCreateSelectIteratorU3Ec__Iterator10_2_t4351 *)__this, method)
// System.Collections.IEnumerator System.Linq.Enumerable/<CreateSelectIterator>c__Iterator10`2<<>f__AnonymousType0`2<System.Reflection.ConstructorInfo,System.Reflection.ParameterInfo[]>,<>f__AnonymousType1`2<<>f__AnonymousType0`2<System.Reflection.ConstructorInfo,System.Reflection.ParameterInfo[]>,System.Collections.Generic.IEnumerable`1<System.Type>>>::System.Collections.IEnumerable.GetEnumerator()
#define U3CCreateSelectIteratorU3Ec__Iterator10_2_System_Collections_IEnumerable_GetEnumerator_m22559(__this, method) (Object_t *)U3CCreateSelectIteratorU3Ec__Iterator10_2_System_Collections_IEnumerable_GetEnumerator_m15290_gshared((U3CCreateSelectIteratorU3Ec__Iterator10_2_t4351 *)__this, method)
// System.Collections.Generic.IEnumerator`1<TResult> System.Linq.Enumerable/<CreateSelectIterator>c__Iterator10`2<<>f__AnonymousType0`2<System.Reflection.ConstructorInfo,System.Reflection.ParameterInfo[]>,<>f__AnonymousType1`2<<>f__AnonymousType0`2<System.Reflection.ConstructorInfo,System.Reflection.ParameterInfo[]>,System.Collections.Generic.IEnumerable`1<System.Type>>>::System.Collections.Generic.IEnumerable<TResult>.GetEnumerator()
#define U3CCreateSelectIteratorU3Ec__Iterator10_2_System_Collections_Generic_IEnumerableU3CTResultU3E_GetEnumerator_m22560(__this, method) (Object_t*)U3CCreateSelectIteratorU3Ec__Iterator10_2_System_Collections_Generic_IEnumerableU3CTResultU3E_GetEnumerator_m15291_gshared((U3CCreateSelectIteratorU3Ec__Iterator10_2_t4351 *)__this, method)
// System.Boolean System.Linq.Enumerable/<CreateSelectIterator>c__Iterator10`2<<>f__AnonymousType0`2<System.Reflection.ConstructorInfo,System.Reflection.ParameterInfo[]>,<>f__AnonymousType1`2<<>f__AnonymousType0`2<System.Reflection.ConstructorInfo,System.Reflection.ParameterInfo[]>,System.Collections.Generic.IEnumerable`1<System.Type>>>::MoveNext()
#define U3CCreateSelectIteratorU3Ec__Iterator10_2_MoveNext_m22561(__this, method) (bool)U3CCreateSelectIteratorU3Ec__Iterator10_2_MoveNext_m15292_gshared((U3CCreateSelectIteratorU3Ec__Iterator10_2_t4351 *)__this, method)
// System.Void System.Linq.Enumerable/<CreateSelectIterator>c__Iterator10`2<<>f__AnonymousType0`2<System.Reflection.ConstructorInfo,System.Reflection.ParameterInfo[]>,<>f__AnonymousType1`2<<>f__AnonymousType0`2<System.Reflection.ConstructorInfo,System.Reflection.ParameterInfo[]>,System.Collections.Generic.IEnumerable`1<System.Type>>>::Dispose()
#define U3CCreateSelectIteratorU3Ec__Iterator10_2_Dispose_m22562(__this, method) (void)U3CCreateSelectIteratorU3Ec__Iterator10_2_Dispose_m15293_gshared((U3CCreateSelectIteratorU3Ec__Iterator10_2_t4351 *)__this, method)
// System.Void System.Linq.Enumerable/<CreateSelectIterator>c__Iterator10`2<<>f__AnonymousType0`2<System.Reflection.ConstructorInfo,System.Reflection.ParameterInfo[]>,<>f__AnonymousType1`2<<>f__AnonymousType0`2<System.Reflection.ConstructorInfo,System.Reflection.ParameterInfo[]>,System.Collections.Generic.IEnumerable`1<System.Type>>>::Reset()
#define U3CCreateSelectIteratorU3Ec__Iterator10_2_Reset_m22563(__this, method) (void)U3CCreateSelectIteratorU3Ec__Iterator10_2_Reset_m15294_gshared((U3CCreateSelectIteratorU3Ec__Iterator10_2_t4351 *)__this, method)
